config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  resources :categories , :performers, :services , :orders




  root to: 'services#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :services , dependent: :destroy 
    
    validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :service
  validates :nameOrder , :service_id, presence: true
end

app/models/performer.rb
class Performer < ApplicationRecord
    has_many :services , dependent: :destroy    
    validates :firstName, :lastName , presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :category
  belongs_to :performer
  has_many :orders , dependent: :destroy 
  validates :name , :category_id, :performer_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  
  def index
    @category = Category.all()
  end

  def new
    @category= Category.new
  end

  def create
    @category=Category.new(category_params)
    @category.save
    redirect_to @category
  end


  def show
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy

    redirect_to categories_path
  end

  def category_params
    params.require(:category).permit(:name)
  end
  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

def index
  @q = Order.ransack(params[:q])
  @order = @q.result(distinct: true)
  respond_to do |format|
    format.html
    format.xlsx
  end
  end

  def new
    @order = Order.new
  end

  def create
    @order=Order.new(order_params)
    @order.save
    redirect_to @order
  end


  def show
  end

  def edit
  end

  def update
    if @order.update(order_params)
      redirect_to @order
    else
      render 'edit'
    end
  end

  def destroy
    @order.destroy
    redirect_to orders_path
  end

  def order_params
    params.require(:order).permit(:nameOrder, :service_id, :created_at)
  end

  def set_order
    @order = Order.find(params[:id])
  end

    
end

app/controllers/performers_controller.rb
class PerformersController < ApplicationController
  before_action :set_performer, only: [:show, :edit, :update, :destroy]

  def index
    @performer = Performer.all()
  end

  def new
    @performer= Performer.new
  end

  def create
    @performer=Performer.new(performer_params)
    @performer.save
    redirect_to @performer
  end


  def show
  end

  def edit
  end

  def update
    if @performer.update(performer_params)
      redirect_to @performer
    else
      render 'edit'
    end
  end

  def destroy
    @performer.destroy
    redirect_to performers_path
  end

  def performer_params
    params.require(:performer).permit(:firstName, :lastName)
  end
  
  def set_performer
    @performer = Performer.find(params[:id])
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
before_action :set_service, only: [:show, :edit, :update, :destroy]

def index
  @service= Service.all()
  end

  def new
    @service = Service.new
  end

  def create
    @service=Service.new(service_params)
    @service.save
    redirect_to @service
  end


  def show
  end

  def edit
  end

  def update
    if @service.update(service_params)
      redirect_to @service
    else
      render 'edit'
    end
  end

  def destroy
    @service.destroy
    redirect_to services_path
  end

  
  def service_params
    params.require(:service).permit(:name, :category_id, :performer_id)
  end

  def set_service
    @service = Service.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/performers_helper.rb
module PerformersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/categories/create.hml.erb
<HTML>
<h1>Categories</h1>
<%= form_with model: @category do |c| %>
  <%= c.text_field :name , placeholder: 'NameCatygory'%>
  <%= c.submit "Send" %>
<% end %>
</html>

app/views/categories/edit.html.erb
<HTML>
<h1>Categories change name</h1>
<%= form_with model: @category do |c| %>
  <%= c.text_field :name , placeholder: 'New_NameCatygory'%>
  <%= c.submit "Send" %>
<% end %>
</html>

app/views/categories/index.html.erb
<h1>Listing Categories </h1>
<table>
 <% @category.each do |category| %>
      <tr>
        <td>CategoryName:</td>
        <td><%= category.name %></td>
        <td>
      <%= link_to 'Show', category %>
      </td>
       <td><%= link_to 'Edit', edit_category_path(category) %></td>
       <td><%= link_to 'Delete', category_path(category),
           method: :delete %></td>
      </tr>
      
  <% end %>
  </table>

app/views/categories/new.html.erb
<HTML>
<h1>Categories</h1>
<%= form_with model: @category do |c| %>
  <%= c.text_field :name , placeholder: 'NameCatygory'%>
  <%= c.submit "Send" %>
<% end %>
</html>

app/views/categories/show.html.erb
<HTML>
<%= form_with model: @category do |c| %>
<p>
  <strong>CategoryName:</strong>
  <%= @category.name %>
</p>
<%end%>
</HTML>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Autoservice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/services/new">Добавить услугу</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/categories/new/">Добавить кaтегурию</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="/categories/create" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Menu
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="/categories">Show Categories</a></li>
            <li><a class="dropdown-item" href="/performers">Show Performers</a></li>
            <li><a class="dropdown-item" href="/services">Show Services</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="/orders">Show Orders</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/orders/new">Создать заказ</a>
        </li>
        <li class="nav-item">
        <li class="nav-item">
          <a class="nav-link" href="/performers/new/">Добавить исполнителя</a>
        </li>
      </ul>

      <!--form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button-->
      </form>
    </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/orders/_search_form.html.erb
<%= search_form_for @q do |f| %>


<%= f.label :nameOrder_cont %>

<%= f.search_field :nameOrder_cont , placeholder: 'Search_by_name_order_or_Service_Name'%>

<%= f.label :created_at_cont %>

<%= f.search_field :created_at_start , placeholder: 'Search_by_DataCreated'%>

<%= f.submit "Search" %>

<%= f.submit 'Save as XSLX',  formaction: orders_path(format: :xlsx) %>

<% end %>

app/views/orders/create.html.erb
<h1>New Order <h1>
<%= form_with model: [@order]  do |c| %>
  <%= c.text_field :nameOrder , placeholder: 'Name_order'%>
  <%= c.label :service_id , "ServiceID:" %>
  <%= c.collection_select :service_id, Service.all, :id, :name %>
  <%= c.submit "Send" %>
<% end %>
</html>

app/views/orders/edit.html.erb
<h1>Edit Order <h1>
<%= form_with model: [@order]  do |c| %>
  <%= c.text_field :nameOrder , placeholder: 'Name_order'%>
  <%= c.label :service_id , "ServiceID:" %>
  <%= c.collection_select :service_id, Service.all, :id, :name %>
  <%= c.submit "Send" %>
<% end %>
</html>

app/views/orders/index.html.erb
<h1>Listing Orders </h1>
<div>Search:<div/>
<%= render "/orders/search_form.html.erb" %>
<strong>All Orders</strong>
<table>
  <thead>
    <tr>
       <th><%= sort_link(@q, :service_id, default_order: :asc) %></th>
       <th><%= sort_link(@q, :nameOrder, "Name", default_order: :asc) %></th>
      <th><%= sort_link(@q, :created_at, "CreatedData", default_order: :desc) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order.each do |order| %>
      <tr>
        <td>ServiceName: </td>
        <td><%= order.service.name %></td>
        <td>OrderName:</td>
        <td><%= order.nameOrder %></td>
        <td><%= order.created_at %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/new.html.erb
<h1>New Order <h1>
<%= form_with model: [@order]  do |c| %>
  <%= c.text_field :nameOrder , placeholder: 'Name_order'%>
  <%= c.label :service_id , "ServiceID:" %>
  <%= c.collection_select :service_id, Service.all, :id, :name %>
  <%= c.submit "Send" %>
<% end %>
</html>

app/views/orders/show.html.erb
<HTML>
<%= form_with model: @order do |c| %>
<p>
  <strong>OrderName:</strong>
  <%= @order.nameOrder %>
   <strong>ServiceID:</strong>
  <%= @order.service_id %>
  <strong>DataCreated:</strong>
  <%=@order.created_at %>
</p>
<%end%>
</HTML>

app/views/performers/create.html.erb
<HTML>
<h1>Performers create</h1>
<%= form_with model: @performer do |c| %>
  <%= c.text_field :firstName , placeholder: 'First_name'%>
  <%= c.text_field :lastName , placeholder: 'Last_name'%>
  <%= c.submit "Send" %>
<% end %>
</html>

app/views/performers/edit.html.erb
<HTML>
<h1>Performers change </h1>
<%= form_with model: @performer do |c| %>
  <%= c.text_field :firstName , placeholder: 'Change_firstName'%>
  <%= c.text_field :lastName , placeholder: 'Change_lastName'%>
  <%= c.submit "Send" %>
<% end %>
</html>

app/views/performers/index.html.erb
<h1>Performers List</h1>
<table>
 <% @performer.each do |performer| %>
      <tr>
        <td>FirstName:</td>
        <td><%=performer.firstName %></td>
        <td>LastName:</td>
        <td><%=performer.lastName %></td>
        <td>
      <%= link_to 'Show', performer %>
      </td>
       <td><%= link_to 'Edit', edit_performer_path(performer) %></td>
       <td><%= link_to 'Delete', performer_path(performer),
           method: :delete %></td>
      </tr>
      
  <% end %>
  </table>

app/views/performers/new.html.erb
<HTML>
<h1>create Performers</h1>
<%= form_with model: @performer do |c| %>
  <%= c.text_field :firstName , placeholder: 'firstName'%>
  <%= c.text_field :lastName , placeholder: 'lastName'%>
  <%= c.submit "Send" %>
<% end %>
</html>

app/views/performers/show.html.erb
<HTML>
<%= form_with model: @performer do |c| %>
<p>
  <strong>FirstName:</strong>
  <%= @performer.firstName %>
  <strong>LastName:</strong>
  <%= @performer.lastName %>
</p>
<%end%>
</HTML>

app/views/services/create.html.erb
<h1>New Service <h1>
<%= form_with model: [@service]  do |c| %>
  <%= c.text_field :name , placeholder: 'Name_service'%>
  <%= c.label :category_id , "CategoryID:" %>
  <%= c.collection_select :category_id, Category.all, :id, :name %>
  <%= c.label :performer_id , "PerformerID:" %>
  <%= c.collection_select :performer_id, Performer.all, :id, :lastName %>
  <%= c.submit "Send" %>
<% end %>
</html>

app/views/services/edit.html.erb
<h1>Edit Service <h1>
<%= form_with(model: Service, local: true) do |c| %>
  <%= c.text_field :name , placeholder: 'Name_service'%>
  <%= c.collection_select :category_id, Category.all, :id, :name %>
   <%= c.collection_select :performer_id, Performer.all, :id, :lastName %>
  <%= c.submit "Send" %>
<% end %>
</html>

app/views/services/index.html.erb
<h1>Listing Services </h1>
<table>
 <% @service.each do |service| %>
      <tr>
        <td>ServiceName:</td>
        <td><%= service.name %></td>
        <td>
      <%= link_to 'Show', service %>
      </td>
       <td><%= link_to 'Edit', edit_service_path(service) %></td>
       <td><%= link_to 'Delete', service_path(service),
           method: :delete %></td>
      </tr>
      
  <% end %>
  </table>

app/views/services/new.html.erb
<h1>New Service <h1>
<%= form_with model: [@service]  do |c| %>
  <%= c.text_field :name , placeholder: 'Name_service'%>
  <%= c.label :category_id , "CategoryID:" %>
  <%= c.collection_select :category_id, Category.all, :id, :name %>
  <%= c.label :performer_id , "PerformerID:" %>
  <%= c.collection_select :performer_id, Performer.all, :id, :lastName %>
  <%= c.submit "Send" %>
<% end %>
</html>

app/views/services/show.html.erb
<HTML>
<%= form_with model: @service do |c| %>
<p>
  <strong>Title:</strong>
  <%= @service.name %>
</p>
<%end%>
</HTML>
<HTML>
<%= form_with model: @service do |c| %>
<p>
  <strong>ServiceName:</strong>
  <%= @service.name %>
   <strong>CategoryID:</strong>
  <%= @service.category_id %>
  <strong>PerformerID:</strong>
  <%= @service.performer_id %>
</p>
<%end%>
</HTML>